language: ruby

services:
  - docker

jobs:
  include:
    - stage: bake docker image
      script:
      - docker build -t sephora .

    - stage: push docker image
      script:
      - docker push deojha1771/sephora:latest

    - stage: test
      script:
      - docker run -dit deojha1771/sephora:latest



