language: ruby

services:
  - docker

jobs:
  include:
    - stage: bake docker image
      script:
      - docker build -t sephora . && docker images

    - stage: tag docker image
      script:
      - docker images && docker tag sephora:latest deojha1771/sephora:latest

    - stage: push docker image
      script:
      - docker push deojha1771/sephora:latest

    - stage: test
      script:
      - docker run -dit deojha1771/sephora:latest



