language: ruby

services:
  - docker

env:
  global:
    - NAME=sephora
    - CACHE_FOLDER=$HOME/docker-images
    - CACHE_FILE=${CACHE_FOLDER}/${NAME}-${TRAVIS_COMMIT}.tgz

jobs:
  include:
    - stage: bake and push docker image
      script:
      - docker build -t sephora .
      - docker tag sephora:latest deojha1771/sephora:latest
      - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - docker push deojha1771/sephora:latest

    - stage: test
      script:
      - docker run -dit deojha1771/sephora:latest





